name: Build & Publish (master)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
            java-version: 1.16
      - name: Gradle (Build)
        run: sh gradlew build
      - name: Upload artifacts (Main JAR)
        uses: actions/upload-artifact@v2
        with:
          name: Main JAR
          path: build/libs/*-all.jar
      - name: Upload artifacts (JARs)
        uses: actions/upload-artifact@v2
        with:
          name: JARs
          path: build/libs/*.jar
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - run: docker build -t ghcr.io/smalauncher/smarollingscraper:latest -t ghcr.io/smalauncher/smarollingscraper:${GITHUB_SHA} .
      - run: docker push ghcr.io/smalauncher/smarollingscraper:latest
      - run: docker push ghcr.io/smalauncher/smarollingscraper:${GITHUB_SHA}
      - name: Push new release to gdude's server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: salt "shimmer.gserv.me" state.apply docker/leo-scraper
          host: ${{ secrets.GSERV_SSH_HOST }}
          port: ${{ secrets.GSERV_SSH_PORT }}
          username: ${{ secrets.GSERV_SSH_USER }}
          privateKey: ${{ secrets.GSERV_SSH_KEY }}
